### PR TITLE
Added Computer Architecture: Quantitative Approach, 6th Edition

### PR DESCRIPTION
**Pull request by Shreesh-Kulkarni**
Added the resource for Quantitative Approach, 6th edition book in the Intermediate section as suggested.

### CODE REVIEW

**Review by KuthumiPepple — CHANGES_REQUESTED** [review]
This looks good. In the end of the description, could you add info about the required background knowledge in parentheses. For example, something like:

*(Required Background: It is recommended that you first read <a href="https://www.amazon.com/Computer-Organization-Design-RISC-V-Architecture/dp/0128203315" target="_blank">the Hardware Software Interface</a> before this book)*

**Comment by Shreesh-Kulkarni** [comment]
I have made the changes.

**Review by KuthumiPepple — CHANGES_REQUESTED** [review]
Could you please add an empty space above the required background info and italicize it as well. (See the description of the previous resource ie. **learn-FPGA II**)

**Review by KuthumiPepple — APPROVED** [review]

**Comment by KuthumiPepple** [comment]
Closes #2

**Pull request merged**
